### ISSUE TITLE
implement device camera feature

### ISSUE THREAD

**Issue by khnguyen88** [rcski77/nannyhelper#8]
Get permission from devices to use onboard camera to take an image and store on local drive. 

//POTENTIAL FUTURE TODOS AND ISSUES

- Will later implement persistent storage on the firebase database and cloud storage (in a different issue?)

- And then take image and use and profile image

**Comment by rcski77** [comment]
//POTENTIAL FUTURE TODOS AND ISSUES

Will later implement persistent storage on the firebase database and cloud storage (in a different issue?)

And then take image and use and profile image
